config/routes.rb
Bus::Application.routes.draw do
  root :to => 'information#start_page'
  resources :tickets, :only => [:index, :show]do
    collection do
      get :search
      get :reservation
      get :ticket_request
    end
  end

  resources :information, :only => [] do 
    collection do
      get :about_us
      get :how_it_works
      get :start_page
    end
  end

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  mount RailsAdmin::Engine => '/admin2', :as => 'rails_admin'
  mount Resque::Server, :at => '/resque'

end

app/models/ticket.rb
#encoding: utf-8

class Ticket < ActiveRecord::Base
  belongs_to :carrier
  
  has_one :one_way_price
  has_one :one_way_visa_price
  has_one :two_ways_price
  has_one :two_ways_visa_price
  has_one :visa_price
  has_one :health_insurance_price

  has_many :ways, :dependent => :destroy
  has_many :cities, :through => :ways

  has_many :departures, :dependent => :destroy
  has_many :departure_dates, :through => :departures

  accepts_nested_attributes_for :health_insurance_price,  :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :visa_price,              :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :one_way_price,           :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :one_way_visa_price,      :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :two_ways_price,          :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :two_ways_visa_price,     :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :departures,              :reject_if => proc { |atr| atr['departure_date_id'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :ways,                    :reject_if => proc { |atr| atr['city_id'].blank? }, :allow_destroy => true

  attr_reader :marshrut, :marshrut_with_detalies, :prt_departure_dates

  def marshrut(from)
    h = Hash.new
    cities.map { |p| h[p.id] = p.name }
    ways.where(:direction => from).collect(&:city_id).map! { |i| i = h[i] } * ' - '
  end

  def marshrut_with_detalies(from)
    h = Hash.new
    cities.map { |p| h[p.id] = p.name }
    "<table><tbody>
      #{ways.where(:direction => from).map! { |i| 
      i = "<tr>
        <td>#{h[i.city_id]}</td>
        <td>#{i.place_stop}</td>
        <td>#{i.time_stop ? i.time_stop.strftime("%H:%M") : "-"}</td>
      </tr>" 
    }.join}</tbody></table>"
  end

  def prt_departure_dates(from)
    mon = Date::MONTHNAMES.compact
    h,b,p = {},{},[]
    departure_dates.map { |p| h[p.id] = p.day_of_life }
    a = departures.where(:direction => from).collect(&:departure_date_id).map! { |i| i = h[i] }
    a.each {|i| b[i.year] = {}}
    a.each {|i| b[i.year][i.mon] = []}
    a.each {|i| b[i.year][i.mon] << i.day}
    b.each { |k,v| 
      p << "<p><b>#{k}</b></p>" 
      v.each { |key, val| 
        p << "<p><i>#{mon[key-1]}</i> - #{val.join(", ")}</p>"
      }
    }
   p.join
  end

  def self.search(params)
    from = City.find(params[:city_from]).country.name == "Україна" ? true : false
    if params[:one_way] == "true"
      one_way_search(params, from, params[:date_from])
    else
      two_ways_search(params, from)
    end
  end

  private

  def self.one_way_search(params, from, date)
    ticket_where_city(params[:city_from], from) & 
    ticket_where_city(params[:city_to], from) &
    find(Departure.where(
      :direction => from, 
      :departure_date_id => departure_date_id_from_date(date)
    ).collect(&:ticket_id))
  end

  def self.ticket_where_city(city_id, from)
    find(Way.where(:direction => from, :city_id => city_id).collect(&:ticket_id))
  end

  def self.departure_date_id_from_date(day)
    DepartureDate.find_by_day_of_life(Date.strptime(day, '%d/%m/%Y')).id
  end

  def self.two_ways_search(params, from)
    @tickets_from = one_way_search(params, from, params[:date_from])
    @tickets_to = one_way_search(params, !from, params[:date_to])
    @tickets = @tickets_to & @tickets_from
    {
      :tickets_to => @tickets_to - @tickets,
      :tickets_from => @tickets_from - @tickets,
      :tickets => @tickets
    }
  end
end

app/controllers/tickets_controller.rb
#encoding: utf-8

class TicketsController < InheritedResources::Base
  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def search
    @tickets = params[:commit] ? Ticket.search(params) : []
    @params = params
  end

  def reservation
    Resque.enqueue_in(2, ReserveNotification, 
      Reservation.create!(params.delete_if { |k,v| 
        ["utf8","commit","action","controller"].include?(k) 
      }).id
    ) if params[:commit]
  end

  def ticket_request
    print params
    Resque.enqueue_in(2, RequestNotification,
      Request.create!(params.delete_if { |k,v| 
        ["utf8","commit","action","controller"].include?(k) 
      }).id
    ) if params[:commit]
  end
end

app/helpers/tickets_helper.rb
#encoding: utf-8

module TicketsHelper
  def cities_for_select
    option_groups_from_collection_for_select(Country.all, :cities, :name, :id, :name)
  end

  def cities_for_select_with(selected)
    option_groups_from_collection_for_select(Country.all, :cities, :name, :id, :name, selected)
  end

  def cities_for_select_js
    escape_javascript(option_groups_from_collection_for_select(Country.all, :cities, :name, :id, :name))
  end

  def cities_for_select_without(city_id)
    option_groups_from_collection_for_select(Country.where("id != ?", City.find(city_id).country.id), :cities, :name, :id, :name)
  end  

  def way(ticket, city_id, from)
    ticket.ways.where(
      :city_id => city_id, 
      :direction => !(from ^ (City.find(city_id).country.name == "Україна" ? true : false))
    ).first
  end
  def departure(ticket, date, city_id, from)
    ticket.departures.where(
      :departure_date_id => departure_date_id_from_date(date), 
      :direction => !(from ^ (City.find(city_id).country.name == "Україна" ? true : false))
    ).first
  end

  def to_time(time)
    time.to_s(:time) if time
  end

  def departure_date_id_from_date(date)
    day_of_life = Date.strptime(date, '%d/%m/%Y')
    DepartureDate.find_by_day_of_life(day_of_life).id
  end
end

app/views/tickets/_all_popups.html.haml
#ticketPopup.modal.fade

#reservePopup.modal.fade
  .modal-header
    %a.close{data:{dismiss:"modal"}} ×
    %h3 Дякуємо, що користуєтесь нашим сервісом.
  .modal-body
    Ваша резервація прийнята і дуже скоро буде розглянута нашим менеджером.
  .modal-footer
    %a.btn{data: {dismiss: "modal"}} Закрити

#requestedPopup.modal.fade
  .modal-header
    %a.close{data:{dismiss:"modal"}} ×
    %h3 Дякуємо, що користуєтесь нашим сервісом.
  .modal-body
    Ваш запит прийнятий і дуже скоро буде розглянутий нашим менеджером.
  .modal-footer
    %a.btn{data: {dismiss: "modal"}} Закрити

#reservationPopup.modal.fade
  .modal-header
    %a.close{data:{dismiss:"modal"}} ×
    = "<b>#{City.find(p[:city_from]).name} (#{City.find(p[:city_from]).country.name}) - #{City.find(p[:city_to]).name} (#{City.find(p[:city_to]).country.name})</b>".html_safe
    - if p[:one_way] == "false"
      = "<b> - #{City.find(p[:city_from]).name} (#{City.find(p[:city_from]).country.name})</b>".html_safe
  .modal-body
    .row-fluid
      .span12
        %ul.thumbnails
          %li.span3.thumbnail
            %p= "Виїзд: <b>#{p[:date_from]}</b>".html_safe
            %p= "Час виїзду: <b id='time_stop_from'></b>".html_safe
            %p= "Місце: <b id='place_stop_from'></b>".html_safe
            %p= "Рейс: <b id='trip_number_from'></b>".html_safe
            - if p[:one_way] == "false"
              %br/
              %p= "<b>Зворотній</b>".html_safe
              %p= "Виїзд: <b>#{p[:date_to]}</b>".html_safe
              %p= "Час виїзду: <b id='time_stop_to'></b>".html_safe
              %p= "Місце: <b id='place_stop_to'></b>".html_safe
              %p= "Рейс: <b id='trip_number_to'></b>".html_safe
          %li.span9.thumbnail
            = form_tag reservation_tickets_path, :class => "form-horizontal", :id => "reservation_form", :method => "get", :remote => true do
              %fieldset
                %legend Оформіть замовлення
                .control-group
                  = label_tag :adult, 'Дорослих по <b id="price_for_adult"></b><b> €</b>'.html_safe, :class => 'control-label'
                  .controls
                    .input-prepend.input-append
                      %span.btn{ :onclick => "minus_adult();"}
                        %i.icon-minus-sign
                      = text_field_tag :adult, 1, :class=>'input-mini'
                      %span.btn{ :onclick => "plus_adult();"}
                        %i.icon-plus-sign
                .control-group
                  = label_tag :child, 'Пільгових* по <b id="price_for_child"></b><b> €</b>'.html_safe, :class => 'control-label'
                  .controls
                    .input-prepend.input-append
                      %span.btn{ :onclick => "minus_child();"}
                        %i.icon-minus-sign
                      = text_field_tag :child, 0, :class=>'input-mini'
                      %span.btn{ :onclick => "plus_child();"}
                        %i.icon-plus-sign
                .control-group
                  = label_tag :price_sum, 'Разом', :class => 'control-label'
                  .controls
                    %span.input-mini.uneditable-input#price_sum 0
                .control-group
                  = label_tag :visa, "Чи бажаєте візу", :class => 'control-label'
                  .controls
                    %label.checkbox
                      = check_box_tag :visa
                      <b>50 +/- 15 €</b>
                .control-group
                  = label_tag :name, "Ваше Ім'я", :class => 'control-label'
                  .controls
                    = text_field_tag :name, '', :class=>'input-medium'
                .control-group
                  = label_tag :email, 'Ваш e-mail', :class => 'control-label'
                  .controls
                    = text_field_tag :email, '', :class=>'input-medium'
                .control-group
                  = label_tag :phone, 'Ваш телефон', :class => 'control-label'
                  .controls
                    .input-prepend
                      %span.add-on +380
                      = text_field_tag :phone, '', :class=>'input-small'
                = hidden_field_tag :city_from_id, p[:city_from]
                = hidden_field_tag :city_to_id, p[:city_to]
                = hidden_field_tag :departure_from_id, ''
                - if p[:one_way] == "false"
                  = hidden_field_tag :departure_to_id, ''
                = hidden_field_tag :one_way, p[:one_way]
                .form-actions
                  = submit_tag "Оформити", :class => "btn btn-success"
                  %a.btn{data: {dismiss: "modal"}} Закрити

app/views/tickets/_empty_search.html.haml
%li.span12.thumbnail.ticket_background{ :class => "pagination-centered" }
  %span 
    %h3 Нажаль потрібних рейсів не знайдено, залиште запит на рейс і наші менеджери спробують вам допомогти
  %span= link_to_function "Залишити запит", "request();", :class => "btn btn-success"

#emptyPopup.modal.fade
  .modal-header
    %a.close{data:{dismiss:"modal"}} ×
    %h3 Запит на рейс
  .modal-body 
    = form_tag ticket_request_tickets_path, :class => "form-horizontal", :id => "ticket_request_form", :method => "get", :remote => true do
      %fieldset
        .control-group
          = label_tag :city_from, "Місто виїзду", :class => 'control-label'
          .controls
            = select_tag :city_from_id, cities_for_select_with(p[:city_from])
        .control-group
          = label_tag :city_to, " Місто прибуття", :class => 'control-label'
          .controls
            = select_tag :city_to_id, cities_for_select_with(p[:city_to])
        .control-group
          = label_tag :one_way, "Тільки туди", :class => 'control-label'
          .controls
            %label.radio
              = radio_button_tag :one_way, true
        .control-group
          = label_tag :one_way, "Туди і назад", :class => 'control-label'
          .controls
            %label.radio
              = radio_button_tag :one_way, false, true
        .control-group
          = label_tag :date_from2, "День виїзду", :class => 'control-label'
          .controls
            = text_field_tag :date_from , p[:date_from], :class => "input-small", :id => 'date_from2'
        .control-group.date_to2
          = label_tag :date_to2, "День повернення", :class => 'control-label'
          .controls
            = text_field_tag :date_to , p[:date_to], :class => "input-small", :id => 'date_to2'
        .control-group
          = label_tag :adult, 'Дорослих', :class => 'control-label'
          .controls
            .input-prepend.input-append
              %span.btn{ :onclick => "minus_adult();"}
                %i.icon-minus-sign
              = text_field_tag :adult, 1, :class=>'input-mini'
              %span.btn{ :onclick => "plus_adult();"}
                %i.icon-plus-sign
        .control-group
          = label_tag :child, 'Пільгових', :class => 'control-label'
          .controls
            .input-prepend.input-append
              %span.btn{ :onclick => "minus_child();"}
                %i.icon-minus-sign
              = text_field_tag :child, 0, :class=>'input-mini'
              %span.btn{ :onclick => "plus_child();"}
                %i.icon-plus-sign
        .control-group
          = label_tag :visa, "Чи бажаєте візу", :class => 'control-label'
          .controls
            %label.checkbox
              = check_box_tag :visa
        .control-group
          = label_tag :name, "Ваше Ім'я", :class => 'control-label'
          .controls
            = text_field_tag :name, '', :class=>'input-medium'
        .control-group
          = label_tag :email, 'Ваш e-mail', :class => 'control-label'
          .controls
            = text_field_tag :email, '', :class=>'input-medium'
        .control-group
          = label_tag :phone, 'Ваш телефон', :class => 'control-label'
          .controls
            .input-prepend
              %span.add-on +380
              = text_field_tag :phone, '', :class=>'input-small'
        .control-group
          = label_tag :email, 'Побажання', :class => 'control-label'
          .controls
            = text_area_tag :notice, '', :class=>'input-large'
        .form-actions
          = submit_tag "Залишити запит", :class => "btn btn-success"

app/views/tickets/_search.html.haml
- if t.any? 
  %ul.thumbnails
    - t.each do |ticket|
      - if ticket.one_way_price
        %li.span2.thumbnail.ticket_background{ :class => "pagination-centered" }
          %h1= "#{ticket.one_way_price.adult} €"
          %p= "Пільговий #{ticket.one_way_price.child} € <span rel='tooltip' title='Діти до 14 років, студенти до 21 року та пенсіонери'><i class='icon-info-sign'></i></span></span>".html_safe
          %p= "Рейс <b>#{departure(ticket, p[:date_from], p[:city_from], true).trip_number}</b>".html_safe
          %p= link_to 'Детальніше', ticket, :remote => true, :class => "btn btn-primary"
          %p= link_to_function "Забронювати", "reservation( '#{ticket.one_way_price.adult}',
                                                      '#{ticket.one_way_price.child}',
                                                      '#{departure(ticket, p[:date_from], p[:city_from], true).trip_number}',
                                                      '#{to_time(way(ticket, p[:city_from], true).time_stop)}',
                                                      '#{way(ticket, p[:city_from], true).place_stop}',
                                                      '#{departure(ticket, p[:date_from], p[:city_from], true).id}')", :class => "btn btn-success"
    - t.each do |ticket|
      - if !ticket.one_way_price && ticket.two_ways_price
        %li.span2.thumbnail.ticket_background{ :class => "pagination-centered" }
          %h1= "<span rel='tooltip' title='Вартість у дві сторони' style='color:red;'>#{ticket.two_ways_price.adult} €</span>".html_safe
          %p= "Пільговий #{ticket.two_ways_price.child} € <span rel='tooltip' title='Діти до 14 років, студенти до 21 року та пенсіонери'><i class='icon-info-sign'></i></span>".html_safe
          %p= "Рейс <b>#{departure(ticket, p[:date_from], p[:city_from], true).trip_number}</b>".html_safe
          %p= link_to 'Детальніше', ticket, :remote => true, :class => "btn btn-primary"
          %p= link_to_function "Забронювати", "reservation( '#{ticket.two_ways_price.adult}',
                                                      '#{ticket.two_ways_price.child}',
                                                      '#{departure(ticket, p[:date_from], p[:city_from], true).trip_number}',
                                                      '#{to_time(way(ticket, p[:city_from], true).time_stop)}',
                                                      '#{way(ticket, p[:city_from], true).place_stop}',
                                                      '#{departure(ticket, p[:date_from], p[:city_from], true).id}')", :class => "btn btn-success"
    
  = render "tickets/all_popups", :p => p
- elsif p[:commit] 
  %ul.thumbnails
    = render "tickets/empty_search", :p => p
- else
  / %ul.thumbnails
  /   = render "tickets/start_block"

app/views/tickets/_search_title.html.haml
- if p[:date_from]
  .alert.alert-success
    = "Рейс на <b>#{p[:date_from]}</b> із <b>#{City.find(p[:city_from]).name} (#{City.find(p[:city_from]).country.name})</b> до <b>#{City.find(p[:city_to]).name} (#{City.find(p[:city_to]).country.name})</b>".html_safe
    - if p[:date_to] != ''
      = "та звортній рейс на <b>#{p[:date_to]}</b>".html_safe

app/views/tickets/_search_two.html.haml
%ul.thumbnails
  - if t.any? 
    - t.each do |ticket|
      - if ticket.two_ways_price
        %li.span2.thumbnail.ticket_background{ :class => "pagination-centered" }
          %h1= "#{ticket.two_ways_price.adult} €"
          %p= "Пільговий #{ticket.two_ways_price.child} €"
          %p= "Туди - рейс <b>#{departure(ticket, p[:date_from], p[:city_from], true).trip_number}</b>".html_safe
          %p= link_to 'Детальніше', ticket, :remote => true, :class => "btn btn-primary"
          %p= "Назад - рейс <b>#{departure(ticket, p[:date_to], p[:city_from], false).trip_number}</b>".html_safe
          %p= link_to 'Детальніше', ticket, :remote => true, :class => "btn btn-primary"
          %p= link_to_function "Забронювати", "reservation( '#{ticket.two_ways_price.adult}',
                                                      '#{ticket.two_ways_price.child}',
                                                      '#{departure(ticket, p[:date_from], p[:city_from], true).trip_number}',
                                                      '#{to_time(way(ticket, p[:city_from], true).time_stop)}',
                                                      '#{way(ticket, p[:city_from], true).place_stop}',
                                                      '#{departure(ticket, p[:date_from], p[:city_from], true).id}',
                                                      '#{departure(ticket, p[:date_to], p[:city_from], false).trip_number}',
                                                      '#{to_time(way(ticket, p[:city_to], false).time_stop)}',
                                                      '#{way(ticket, p[:city_to], false).place_stop}',
                                                      '#{departure(ticket, p[:date_to], p[:city_from], false).id}')", :class => "btn btn-success"
  - if t_to.any? and t_from.any?
    - t_to.each do |ticket_to|
      - t_from.each do |ticket_from|
        - if ticket_to.one_way_price && ticket_from.one_way_price
          %li.span2.thumbnail.ticket_background{ :class => "pagination-centered" }
            %h1= "#{ticket_to.one_way_price.adult + ticket_from.one_way_price.adult} €"
            %p= "Пільговий #{ticket_to.one_way_price.child + ticket_from.one_way_price.child} €"
            %p= "Туди - рейс <b>#{departure(ticket_from, p[:date_from], p[:city_from], true).trip_number}</b>".html_safe
            %p= link_to 'Детальніше', ticket_from, :remote => true, :class => "btn btn-primary"
            %p= "Назад - рейс <b>#{departure(ticket_to, p[:date_to], p[:city_from], false).trip_number}</b>".html_safe
            %p= link_to 'Детальніше', ticket_to, :remote => true, :class => "btn btn-primary"
            %p= link_to_function "Забронювати", "reservation( '#{ticket_to.one_way_price.adult + ticket_from.one_way_price.adult}',
                                                        '#{ticket_to.one_way_price.child + ticket_from.one_way_price.child}',
                                                        '#{departure(ticket_from, p[:date_from], p[:city_from], true).trip_number}',
                                                        '#{to_time(way(ticket_from, p[:city_from], true).time_stop)}',
                                                        '#{way(ticket_from, p[:city_from], true).place_stop}',
                                                        '#{departure(ticket_from, p[:date_from], p[:city_from], true).id}',
                                                        '#{departure(ticket_to, p[:date_to], p[:city_from], false).trip_number}',
                                                        '#{to_time(way(ticket_to, p[:city_to], false).time_stop)}',
                                                        '#{way(ticket_to, p[:city_to], false).place_stop}',
                                                        '#{departure(ticket_to, p[:date_to], p[:city_from], false).id}')", :class => "btn btn-success"
  - if t_to.any? and t_from.any? or t.any?
    = render "tickets/all_popups", :p => p
  - else
    = render "tickets/empty_search", :p => p

app/views/tickets/_show.html.haml
.modal-header
  %a.close{data:{dismiss:"modal"}} ×
  %h3 
    #{ticket.cities.first.country.name} - #{ticket.cities.last.country.name} - #{ticket.cities.first.country.name}
.modal-body
  .row-fluid.book
    .span12
      %ul.thumbnails
        %li.span3.thumbnail{ :class => "pagination-centered" }
          - if ticket.one_way_price
            %p 
              %b В один бік:
            %h2= "<b>#{ticket.one_way_price.adult} €</b>".html_safe
            %p= "Пільговий* - <b>#{ticket.one_way_price.child} €</b>".html_safe
          - if ticket.two_ways_price
            %p
              %b В два боки:
            %h2= "<b>#{ticket.two_ways_price.adult} €</b>".html_safe
            %p= "Пільговий* - <b>#{ticket.two_ways_price.child} €</b>".html_safe
        %li.span9.thumbnail
          %p 
            %b Маршрут з України:
            = ticket.marshrut(true).html_safe
          %p 
            %b Маршрут до України:
            = ticket.marshrut(false).html_safe
          %p 
            %b Календар виїздів з України:
          = ticket.prt_departure_dates(true).html_safe
          %p 
            %b Календар виїздів до України:
          = ticket.prt_departure_dates(false).html_safe
.modal-footer
  %a.btn{data: {dismiss: "modal"}} Закрити

app/views/tickets/_start_block.html.haml
%li.span12.thumbnail{ :class => "pagination-centered" }
  %h3 Тут стартова сторінка

app/views/tickets/reservation.js.erb
$('#reservationPopup').modal('hide');
$('#reservePopup').modal('show');

app/views/tickets/search.html.haml
.row
  .span12
    .row
      .span99
        .search_form
          = form_tag search_tickets_path, :id => "search_form", :class => "well form-horizontal", :method => "get", :remote => true do
            %fieldsets
              .control-group
                = label_tag :city_from, "Місто виїзду", :class => 'control-label'
                .controls
                  = select_tag :city_from, cities_for_select, { :onchange => "for_delete_county('#{cities_for_select_js}',$(this).val(), 1);", :prompt => 'Оберіть...', :class => 'required' }
              .control-group
                = label_tag :city_to, "Місто прибуття", :class => 'control-label'
                .controls
                  = select_tag :city_to, cities_for_select, { :onchange => "for_delete_county('#{cities_for_select_js}',$(this).val(), 0);", :prompt => 'Оберіть...' }
              .control-group
                = label_tag :one_way, "Тільки туди", :class => 'control-label'
                .controls
                  %label.radio
                    = radio_button_tag :one_way, true
              .control-group
                = label_tag :one_way, "Туди і назад", :class => 'control-label'
                .controls
                  %label.radio
                    = radio_button_tag :one_way, false, true
              .control-group
                = label_tag :date_from, "Виїзд", :class => 'control-label'
                .controls
                  = text_field_tag :date_from , '', :class => "input-small", :placeholder => "Оберіть..."
              .control-group
                = label_tag :date_to, "Повернення", :class => 'control-label'
                .controls
                  = text_field_tag :date_to , '', :class => "input-small", :placeholder => "Оберіть..."
              .form-actions
                = submit_tag "Шукати рейс", :class => "btn btn-primary"
      .span100
        %img{ :id => "placeholder_img", :src=>"http://placehold.it/760x290" }
        
        
    #search_title
      = render "tickets/search_title", :p => @params 

    #trips
      = render "tickets/search", :t => @tickets, :p => @params

app/views/tickets/search.js.erb
<% if @params[:one_way] == "true" %>
  $("#trips").html(" <%= escape_javascript(render('tickets/search', :t => @tickets, :p => @params)) %>")
<% else %>
  $("#trips").html(" <%= escape_javascript(render('tickets/search_two', :t => @tickets[:tickets], :t_to => @tickets[:tickets_to], :t_from => @tickets[:tickets_from], :p => @params)) %>")
<% end %>

$("#search_title").html("<%= escape_javascript(render('tickets/search_title', :t => @tickets, :p => @params)) %>")

app/views/tickets/show.js.erb
$("#ticketPopup").html("<%= escape_javascript(render('tickets/show', :ticket => @ticket)) %>");
$('#ticketPopup').modal('show');

app/views/tickets/ticket_request.js.erb
$('#emptyPopup').modal('hide');
$('#requestedPopup').modal('show');