config/routes.rb
Bus::Application.routes.draw do
  root :to => 'information#start_page'
  resources :tickets, :only => [:index, :show]do
    collection do
      get :search
      get :reservation
      get :ticket_request
    end
  end

  resources :information, :only => [] do 
    collection do
      get :about_us
      get :how_it_works
      get :start_page
    end
  end

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  mount RailsAdmin::Engine => '/admin2', :as => 'rails_admin'
  mount Resque::Server, :at => '/resque'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  belongs_to :city
  has_many :tickets
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :country
  has_many :carriers
  has_many :ways
  has_many :tickets, :through => :ways
end

app/models/country.rb
class Country < ActiveRecord::Base
	default_scope :order => 'name ASC'
  has_many :cities
end

app/models/departure.rb
class Departure < ActiveRecord::Base
  belongs_to :departure_date
  belongs_to :ticket
end

app/models/departure_date.rb
class DepartureDate < ActiveRecord::Base
  has_many :departures, :dependent => :destroy
  has_many :tickets, :through => :departures
  
  def self.new_day_in_day_of_life
    create!(:day_of_life => order("day_of_life ASC").last.day_of_life + 1)
  end
  def self.destroy_today_from_day_of_life
    where("day_of_life <= ?", Time.now.to_date).destroy_all
  end
end

app/models/one_way_price.rb
class OneWayPrice < ActiveRecord::Base
  belongs_to :ticket
end

app/models/one_way_visa_price.rb
class OneWayVisaPrice < ActiveRecord::Base
  belongs_to :ticket
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :city_from, :class_name => "City"
  belongs_to :city_to, :class_name => "City"
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :city_from, :class_name => "City"
  belongs_to :city_to, :class_name => "City"
  belongs_to :departure_from, :class_name => "Departure"
  belongs_to :departure_to, :class_name => "Departure"
end

app/models/ticket.rb
#encoding: utf-8

class Ticket < ActiveRecord::Base
  belongs_to :carrier
  
  has_one :one_way_price
  has_one :one_way_visa_price
  has_one :two_ways_price
  has_one :two_ways_visa_price
  has_one :visa_price
  has_one :health_insurance_price

  has_many :ways, :dependent => :destroy
  has_many :cities, :through => :ways

  has_many :departures, :dependent => :destroy
  has_many :departure_dates, :through => :departures

  accepts_nested_attributes_for :health_insurance_price,  :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :visa_price,              :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :one_way_price,           :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :one_way_visa_price,      :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :two_ways_price,          :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :two_ways_visa_price,     :reject_if => proc { |atr| atr['adult'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :departures,              :reject_if => proc { |atr| atr['departure_date_id'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :ways,                    :reject_if => proc { |atr| atr['city_id'].blank? }, :allow_destroy => true

  attr_reader :marshrut, :marshrut_with_detalies, :prt_departure_dates

  def marshrut(from)
    h = Hash.new
    cities.map { |p| h[p.id] = p.name }
    ways.where(:direction => from).collect(&:city_id).map! { |i| i = h[i] } * ' - '
  end

  def marshrut_with_detalies(from)
    h = Hash.new
    cities.map { |p| h[p.id] = p.name }
    "<table><tbody>
      #{ways.where(:direction => from).map! { |i| 
      i = "<tr>
        <td>#{h[i.city_id]}</td>
        <td>#{i.place_stop}</td>
        <td>#{i.time_stop ? i.time_stop.strftime("%H:%M") : "-"}</td>
      </tr>" 
    }.join}</tbody></table>"
  end

  def prt_departure_dates(from)
    mon = Date::MONTHNAMES.compact
    h,b,p = {},{},[]
    departure_dates.map { |p| h[p.id] = p.day_of_life }
    a = departures.where(:direction => from).collect(&:departure_date_id).map! { |i| i = h[i] }
    a.each {|i| b[i.year] = {}}
    a.each {|i| b[i.year][i.mon] = []}
    a.each {|i| b[i.year][i.mon] << i.day}
    b.each { |k,v| 
      p << "<p><b>#{k}</b></p>" 
      v.each { |key, val| 
        p << "<p><i>#{mon[key-1]}</i> - #{val.join(", ")}</p>"
      }
    }
   p.join
  end

  def self.search(params)
    from = City.find(params[:city_from]).country.name == "Україна" ? true : false
    if params[:one_way] == "true"
      one_way_search(params, from, params[:date_from])
    else
      two_ways_search(params, from)
    end
  end

  private

  def self.one_way_search(params, from, date)
    ticket_where_city(params[:city_from], from) & 
    ticket_where_city(params[:city_to], from) &
    find(Departure.where(
      :direction => from, 
      :departure_date_id => departure_date_id_from_date(date)
    ).collect(&:ticket_id))
  end

  def self.ticket_where_city(city_id, from)
    find(Way.where(:direction => from, :city_id => city_id).collect(&:ticket_id))
  end

  def self.departure_date_id_from_date(day)
    DepartureDate.find_by_day_of_life(Date.strptime(day, '%d/%m/%Y')).id
  end

  def self.two_ways_search(params, from)
    @tickets_from = one_way_search(params, from, params[:date_from])
    @tickets_to = one_way_search(params, !from, params[:date_to])
    @tickets = @tickets_to & @tickets_from
    {
      :tickets_to => @tickets_to - @tickets,
      :tickets_from => @tickets_from - @tickets,
      :tickets => @tickets
    }
  end
end

app/models/two_ways_price.rb
class TwoWaysPrice < ActiveRecord::Base
  belongs_to :ticket
end

app/models/visa_price.rb
class VisaPrice < ActiveRecord::Base
  belongs_to :ticket
end

app/models/way.rb
class Way < ActiveRecord::Base
  default_scope :order => 'created_at ASC'
  belongs_to :city
  belongs_to :ticket
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/tickets_helper.rb
#encoding: utf-8

module TicketsHelper
  def cities_for_select
    option_groups_from_collection_for_select(Country.all, :cities, :name, :id, :name)
  end

  def cities_for_select_with(selected)
    option_groups_from_collection_for_select(Country.all, :cities, :name, :id, :name, selected)
  end

  def cities_for_select_js
    escape_javascript(option_groups_from_collection_for_select(Country.all, :cities, :name, :id, :name))
  end

  def cities_for_select_without(city_id)
    option_groups_from_collection_for_select(Country.where("id != ?", City.find(city_id).country.id), :cities, :name, :id, :name)
  end  

  def way(ticket, city_id, from)
    ticket.ways.where(
      :city_id => city_id, 
      :direction => !(from ^ (City.find(city_id).country.name == "Україна" ? true : false))
    ).first
  end
  def departure(ticket, date, city_id, from)
    ticket.departures.where(
      :departure_date_id => departure_date_id_from_date(date), 
      :direction => !(from ^ (City.find(city_id).country.name == "Україна" ? true : false))
    ).first
  end

  def to_time(time)
    time.to_s(:time) if time
  end

  def departure_date_id_from_date(date)
    day_of_life = Date.strptime(date, '%d/%m/%Y')
    DepartureDate.find_by_day_of_life(day_of_life).id
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Бронювання чартерних автобусних рейсів
    %meta{ :name => "keywords", :content => "Болгарія, автобус в Болгарію, квитки на автобус в Болгарію, чартерні рейси, автобусні квитки до Болгарії" }
    %meta{ :name => "description", :content => "Бронювання чартерних автобусних рейсів до Болгарії" }
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    /[if gte IE 9]
      :css
        body {
          filter: none;
        }
    %link{:href => "/assets/logo.ico", :rel => "shortcut icon", :type => "image/x-icon"}
  %body
    .container
      .row
        .span12
          %img.logo{:src => '/assets/logo.png' }
            %p.title Бронювання чартерних автобусних рейсів.
      .navbar
        .navbar-inner
          .container
            %a.btn.btn-navbar{ :'data-toggle' => "collapse", :'data-target' => ".nav-collapse" }
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand{ :href => root_path }
              Bus Guide
            .nav-collapse
              %ul.nav
                %li.divider-vertical
                %li{class: current_page?(root_path) && 'active'}= link_to "Головна", :root
                %li.divider-vertical
                %li{class: current_page?(search_tickets_path) && 'active'}= link_to "Знайти рейс", search_tickets_path
                %li.divider-vertical
                %li{class: current_page?(about_us_information_index_path) && 'active'}= link_to "Про нас", about_us_information_index_path
                %li.divider-vertical
                %li{class: current_page?(how_it_works_information_index_path) && 'active'}= link_to "Як це працює", how_it_works_information_index_path 
                %li.divider-vertical
              %ul.nav.pull-right
                / %li{class: request.path.split('/')[1] == "my" && 'active'}= link_to "My Cabinet", [:cabinet, :reservations]
                / %li.divider-vertical
                / %li= link_to "Logout", :destroy_user_session, :method => :delete
      

      = render 'shared/flash'
      = yield
      .push25

      .footer
        .delimeter.top
        .footer_content
          \© 2012
          = succeed "." do
            %a{:href => "http://mongrasse.com.ua", :target => "_blank", :title => "Туристична компанія Монграссе"} TK Mongrasse
          Created by 
          %a{:target => '_blank', :href => "http://www.linkedin.com/pub/viktor-oleksyn/44/573/954"} Viktor Oleksyn
      .push25
    / = render 'shared/feedback'

app/views/shared/_feedback.html.haml
:javascript
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/2mm0QWLLyTQqsWLvQRI4A.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();

app/views/shared/_flash.html.haml
.flash
  - if alert
    .alert.alert-error
      %a.close{data:{dismiss:"alert"}, href:"#"} ×
      = alert
  - if notice
    .alert.alert-success
      %a.close{data:{dismiss:"alert"}, href:"#"} ×
      = notice